name: DockerSR Alpine
on:
  push:
    paths:
      - "gs/os-loc-alpine-lc"
      - "gs/ver_LunarCore-Original-1.5.0"
      - "gs/run.sh"
      - "gs/entrypoint_lc.sh"
      - ".github/workflows/alpine.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync DockerSR
        uses: actions/checkout@v3
      - name: Sync LunarCore
        uses: actions/checkout@v3
        with:
          repository: YuukiPS/LunarCore-Original
          ref: "1.5.0"
          path: sr/LunarCore-Original
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "17"
          cache: "gradle"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USER}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: Build Local Jar
        run: cd sr && chmod +x run.sh && sh run.sh alpine build 0 docker_action pv
      - name: Build Image Docker and Push
        uses: docker/build-push-action@v3
        with:
          context: ./sr
          file: ./sr/os-loc-alpine-lc
          push: true
          tags: |
            ${{ env.ver1 }}
            ${{ env.ver2 }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
