name: YuukiSR
on:
  push:
    paths:
      - "sr/os-loc-alpine-lc"
      - "sr/ver_LunarCore-Private-2.3.0"
      - "sr/run.sh"
      - "sr/entrypoint_lc.sh"
      - ".github/workflows/yuukips.yml"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Sync DockerSR
        uses: actions/checkout@v3
      - name: Sync LunarCore Private
        uses: actions/checkout@v3
        with:
          repository: YuukiPS/LunarCore-Private
          ref: "2.3.0"
          token: ${{ secrets.HUB_TOKEN }} # tes
          path: sr/LunarCore-Private
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: "17"
          cache: "gradle"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: registry.gitlab.com
          username: ${{secrets.DOCKER_USER_PRIVATE_GITLAB}}
          password: ${{secrets.DOCKER_PASSWORD_PRIVATE_GITLAB}}
      - name: Build Local Jar
        run: cd sr && chmod +x run.sh && sh run.sh alpine build 6 docker_action
      - name: Build Image Docker and Push
        uses: docker/build-push-action@v3
        with:
          context: ./sr
          file: ./sr/os-loc-alpine-lc
          push: true
          tags: |
            ${{ env.ver1 }}
            ${{ env.ver2 }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
